export const WEBAPPLICATION_SCHEMA_DATA = {
  descriptions: {
    ko: '개인의 과거, 현재, 미래를 시각적으로 관리하는 타임라인 애플리케이션',
    en: 'A timeline application for visually managing your past, present, and future',
    ja: '個人の過去、現在、未来を視覚的に管理するタイムラインアプリケーション',
    fr: 'Une application de timeline pour gérer visuellement votre passé, présent et futur',
    es: 'Una aplicación de línea de tiempo para gestionar visualmente tu pasado, presente y futuro',
    'zh-cn': '一个可视化管理您的过去、现在和未来的时间线应用程序',
  },
  featureLists: {
    ko: ['타임라인 시각화', '일정 관리', '과거 기록 추적', '다국어 지원', '반응형 디자인'],
    en: [
      'Timeline Visualization',
      'Schedule Management',
      'Past Record Tracking',
      'Multi-language Support',
      'Responsive Design',
    ],
    ja: ['タイムライン視覚化', 'スケジュール管理', '過去記録追跡', '多言語サポート', 'レスポンシブデザイン'],
    fr: [
      'Visualisation Timeline',
      'Gestion Planning',
      'Suivi Enregistrements Passés',
      'Support Multi-langues',
      'Design Responsive',
    ],
    es: [
      'Visualización Timeline',
      'Gestión Horarios',
      'Seguimiento Registros Pasados',
      'Soporte Multi-idioma',
      'Diseño Responsive',
    ],
    'zh-cn': ['时间线可视化', '日程管理', '过去记录跟踪', '多语言支持', '响应式设计'],
  },
  browserRequirements: {
    ko: 'JavaScript가 필요합니다. 최신 브라우저에 최적화되어 있습니다.',
    en: 'Requires JavaScript. Optimized for modern browsers.',
    ja: 'JavaScriptが必要です。モダンブラウザに最適化されています。',
    fr: 'Nécessite JavaScript. Optimisé pour les navigateurs modernes.',
    es: 'Requiere JavaScript. Optimizado para navegadores modernos.',
    'zh-cn': '需要JavaScript。针对现代浏览器进行了优化。',
  },
  langMap: {
    ko: 'ko-KR',
    en: 'en-US',
    ja: 'ja-JP',
    fr: 'fr-FR',
    es: 'es-ES',
    'zh-cn': 'zh-CN',
  },
  currencyMap: {
    ko: 'KRW',
    en: 'USD',
    ja: 'JPY',
    fr: 'EUR',
    es: 'EUR',
    'zh-cn': 'CNY',
  },
};
